env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
  import/prefer-default-export:
    - off
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
  no-underscore-dangle: off
  class-methods-use-this: [ error, { exceptMethods: [ 'render' ] } ]
  '@typescript-eslint/member-ordering':
    - error
  '@typescript-eslint/naming-convention': [ error, {
    "selector": "memberLike",
    "modifiers": [ "private" ],
    "format": [ "camelCase" ],
    "leadingUnderscore": "require"
  } ]